### ISSUE TITLE
Merge perspective.el and persp-mode.el

### ISSUE THREAD

**Issue by conao3** [nex3/perspective-el#111]
cc @Bad-ptr

I agree this comment.
https://github.com/nex3/perspective-el/issues/88#issuecomment-513996542

`perspective.el` and `persp-mode.el` provide almost the same feature but there are also different features.

If we can add some options so that users of these two packages don't bother, new persp-mode user don't have to worry about which package to use.
Two package naming have confusing ( https://github.com/tumashu/posframe/issues/29#issuecomment-495851905 ) and MELPA thought is below see [top page](https://melpa.org/#/).
- Up-to-date packages built on our servers from upstream source
- Installable in any Emacs with 'package.el' - no local version-control tools needed
- Curated - no obsolete, renamed, **forked or randomly hacked packages**
- Comprehensive - more packages than any other archive
- Automatic updates - new commits result in new packages
- Extensible - contribute recipes via github, and we'll build the packages

**Comment by gcv** [comment]
There's definitely a lot to be said for eliminating the confusion caused by two packages. A good start would be to figure out exactly where the two differ.

**Comment by gcv** [comment]
This seems very unlikely to happen.
