### ISSUE TITLE
perspective selection in header line with mouse

### ISSUE THREAD

**Issue by FabArd** [nex3/perspective-el#127]
I'd rather have the name of the perspectives in the header line.

(setq persp-show-modestring 'header)

When this option is activated it is impossible to select the names with the mouse whereas when option mode line is activated it is possible.

Here are the modifications I've made to solve this problem :

(defconst persp-header-line-map
  (let ((map (make-sparse-keymap)))
    (define-key map [header-line down-mouse-1] 'persp-mode-line-click)
    map))

(defun persp-format-name (name)
  "Format the perspective name given by NAME for display in the modeline or headerline."
  (let ((string-name (format "%s" name)))
    (if (equal name (persp-current-name))
        (propertize string-name 'face 'persp-selected-face)
      (cond ((eq persp-show-modestring 'header)
             (propertize string-name
                         'local-map persp-header-line-map
                         'mouse-face 'header-line-highlight))
            ((eq persp-show-modestring t)
             (propertize string-name
                         'local-map persp-mode-line-map
                         'mouse-face 'mode-line-highlight))))))

**Comment by gcv** [comment]
Looks good. Want to open a PR?

**Comment by FabArd** [comment]
Yes.
Can you do it, or can you tell me how to do it ?
I'm not familiar with git !

**Comment by gcv** [comment]
Done in https://github.com/nex3/perspective-el/commit/c869e23c02c6339de998c573c72b34b27b72ec4e.

I gave you credit in the commit message.

The patch should appear in MELPA in the next build. Let me know if you need this tagged for MELPA Stable also.
