### ISSUE TITLE
Creating new scratch buffer sometimes prevents emacsclient from working

### ISSUE THREAD

**Issue by aaronjensen** [nex3/perspective-el#128]
I'm not sure what the exact repro is, but occasionally I get into a state where if I open a file via emacsclient, it will immediate quit with an error saying that the `*scratch* (my-persp)` buffer already exists.

If I switch away from a persp buffer in my main frame and try again, it works.

**Comment by aaronjensen** [comment]
Also, there are other strange behaviors, like if it does successfully open a new frame and I close that frame with `C-x C-#`, it will change the layout of the main frame and actually put `Minibuf-1` in one of my main window areas. If persp-mode is disabled, this does not occur.

**Comment by gcv** [comment]
Do these problems only occur when you use multiple frames? Also, what do you mean by "switch away from a persp buffer in my main frame" — not sure what is a persp buffer? Is your emacsclient rigged to open files in a brand-new frame?

**Comment by aaronjensen** [comment]
> Do these problems only occur when you use multiple frames?

Yes, I use either `emacsclient --tty`, or, when I was reproducing this `emacsclient -c`

> not sure what is a persp buffer? 

Sorry, that wasn't clear, and that's in part because the repro itself wasn't clear to me. Basically, if I go to back to the scratch buffer for a persp, the repro doesn't seem to happen.

> Please post any emacsclient / server configuration you use. I have some suspicions about what might be happening here, but need specifics to try to reproduce the problem.
 
I have a GUI frame that starts the server with `server-start`. I then, from the terminal, open new frames, typically tty frames against the same server.

I have it reproing right now. The issue appears to be the scratch buffer rename in `persp-rename`.

If I comment that out, it doesn't fail. It's attempting to rename `*scratch*` to `*scratch* (.emacs.d)`, which already exists.

**Comment by gcv** [comment]
Why is emacsclient triggering persp-rename? Or is that unrelated?

**Comment by aaronjensen** [comment]
Here's the stack trace:

```
Debugger entered: nil
  persp-rename(".emacs.d")
  ad-Advice-persp-init-frame(#f(compiled-function (frame) "Initialize the perspectives system in FRAME.\nBy default, this uses the current frame." #<bytecode 0x1febc86833d1>) #<frame F12 0x7faef665f5b0>)
  apply(ad-Advice-persp-init-frame #f(compiled-function (frame) "Initialize the perspectives system in FRAME.\nBy default, this uses the current frame." #<bytecode 0x1febc86833d1>) #<frame F12 0x7faef665f5b0>)
  persp-init-frame(#<frame F12 0x7faef665f5b0>)
  run-hook-with-args(persp-init-frame #<frame F12 0x7faef665f5b0>)
  make-frame(((window-system) (tty . "/dev/ttys002") (tty-type . "xterm-24bit") (client . #<process server <12>>) (environment )))
  server-create-tty-frame("/dev/ttys002" "xterm-24bit" #<process server <12>>)
  server-process-filter(#<process server <12>> "-env ...")
```

**Comment by aaronjensen** [comment]
Ah! It's persp-projectile that's the problem:

https://github.com/bbatsov/persp-projectile/blob/master/persp-projectile.el#L101

**Comment by aaronjensen** [comment]
Okay, I believe that it's actually a bug in persp-projectile. That advice is completely broken—it shouldn't need to rename a persp if it's already correct and new frames actually start with the buffer of the previous frame as well as the persp, even when launched from emacsclient,

So: 

1. Frame 1 is on persp `.emacs.d` and in a file that is in the projectile project `.emacs.d`
2. `emacsclient --tty foo` in any projectile directory that isn't `.emacs.d` results in...
3. The advice attempts to rename the `.emacs.d` persp to `.emacs.d` which fails

So:

`perspective.el` could detect a no-op rename and not fail, which would solve this problem indirectly and may not be a bad idea anyway.

And/or `persp-projectile` could fix/remove the bad advice.

In the interim, this fixes it for me: `(ad-deactivate 'persp-init-frame)`

**Comment by gcv** [comment]
Spectacular debugging. Thanks!

I don't use persp-projectile (though I do use and like Projectile itself) and never than into this problem. It's easy to reproduce just by getting a new frame and renaming its `main` perspective to one that already exists on another frame. Since independent perspectives in different frames is a distinguishing feature of Perspective from the [persp-mode fork](https://github.com/Bad-ptr/persp-mode.el), it's important for it not to break.

I have a two-part fix: https://github.com/nex3/perspective-el/commit/4998c1184dba3e9e18e2f3d9153a4a03797c1940 and 4a81843. It should be in MELPA now. Let me know if it works.

**Comment by aaronjensen** [comment]
Looks like that worked, thank you!
