### ISSUE TITLE
Helm support broken since v3.6.3

### ISSUE THREAD

**Issue by JuanGarcia345** [nex3/perspective-el#131]
Hi!

Thank you very much for this handy package. Unfortunately, since version 3.6.3 of `Helm` (commit [f7fa3a9e](https://github.com/emacs-helm/helm/commit/f7fa3a9e0ef1f69c42e0c513d02c9f76ea9a4344)) the buffers list is not created with `Ido` anymore, this breaks `perspective-el` support for `Helm`. Is there any way to circumvent this issue? 

Thank you!

**Comment by gcv** [comment]
Thank you for bringing this to my attention. I pushed a workaround with commit c2d3542, which seems to work for me as expected. It is now available in MELPA. Could you please try it and let me know if it works?

**Comment by JuanGarcia345** [comment]
It works like a charm! Thank you very much.
