### ISSUE TITLE
Automatically loading state from a file in my .emacs

### ISSUE THREAD

**Issue by stugots** [nex3/perspective-el#132]
I want to load a state (currently I have only one, `main`) when Emacs starts.  I tried this in my `./emacs`:
```
(use-package perspective
  :config
  (persp-mode)
  (setq persp-state-default-file "~/.emacs.d/perspective_save")
  ;; Load all perspectives from the save file, and enable persp-mode.
  (persp-state-load "~/.emacs.d/perspective_save")
  (persp-state-switch "main")
  ;; Automatically save perspective session when Emacs exists.
  (add-hook 'kill-emacs-hook #'persp-state-save)
  )
```
...but it doesn't work.  I still have to do a `C-x x C-l` to load the file and automatically switch to `main`.

What am I doing wrong?

**Comment by gcv** [comment]
You might be getting burned by `use-package` lazy loading semantics. What if you add `:defer nil` before the `:config` form?

If that doesn’t work, maybe take a look at the `*Messages*` buffer after startup and look for errors?

**Comment by stugots** [comment]
Duh, `*Messages*`! I had a typo ("perps-state-switch")!

I fixed that and also added an `:ensure t`.  But, still no good. :(

I'll try a version of my `.emacs` with virtually everything else deleted later today.

Here's the current code:
```
(use-package perspective
  :ensure t
  :config
  (persp-mode)
  (setq persp-state-default-file "~/.emacs.d/perspective_save")
  ;; Load all perspectives from the save file, and enable persp-mode.
  (persp-state-load "~/.emacs.d/perspective_save")
  (persp-switch "main")
  ;; Automatically save perspective session when Emacs exists.
  (add-hook 'kill-emacs-hook #'persp-state-save)
  )
```

**Comment by gcv** [comment]
`:ensure t` will not help here; it does package installation, not loading, and you already have the package installed. I think you’re running into trouble with deferred loading. So try some combination of `:defer nil` and `:demand t`, especially if you have `use-package-always-defer` set to `t`. If that doesn’t work, I’ll try to reproduce your setup locally and I’m sure we’ll figure it out.

**Comment by stugots** [comment]
Adding `:defer nil` and `:demand t` did the trick.  Thank you!
