### ISSUE TITLE
Perspective work kill workspace

### ISSUE THREAD

**Issue by Randy1Burrell** [nex3/perspective-el#144]
I have been using perspective for a few weeks now. Pretty neat package, but I have encountered a problem. Whenever I try to invoke persp-kill I get the following error:

```
run-hooks: Wrong number of arguments: (1 . 1), 0
```

Here's my configuration
```emacs-lisp
(use-package perspective
  :config
  (setq persp-state-default-file "~/.emacs.d/persp-confs/persp-auto-save")
  (persp-mode)
  :bind (("s-b" . persp-counsel-switch-buffer)
         ("s-M-b" . persp-ivy-switch-buffer)
         ("C-x b" . persp-switch-to-buffer*)
         ("C-x k" . persp-kill-buffer*)))

(add-hook 'kill-emacs-hook #'persp-state-save)

```

**Comment by Randy1Burrell** [comment]
Sure, `persp-killed-hook` returns `(treemacs--on-scope-kill)` which returns `nil` when evaluated.

The perspective installation is up to date. I tried reinstalling fresh copies more than once before I submitted this issue.

Based on the return value, and having `treemacs` and `treemacs-perspective` packages installed, do you think this might be an integration issue between these three packages?

**Comment by gcv** [comment]
It crashes because of the way treemacs-perspective calls the hook. You are probably the first one to have ever run that code path. :)

Try this implementation of `persp-kill`, which will just overwrite the one in Perspective with one that calls `persp-killed-hook` with an argument:

```
(defun persp-kill (name)
  "Kill the perspective given by NAME.

Killing a perspective means that all buffers associated with that
perspective and no others are killed."
  (interactive "i")
  (if (null name) (setq name (persp-prompt (persp-current-name) t)))
  (with-perspective name
    (condition-case nil
        (run-hooks 'persp-killed-hook)
      (wrong-number-of-arguments (run-hook-with-args 'persp-killed-hook name)))
    (mapc 'persp-remove-buffer (persp-current-buffers))
    (setf (persp-killed (persp-curr)) t))
  (remhash name (perspectives-hash))
  (persp-update-modestring)
  (when (and (persp-last) (equal name (persp-name (persp-last))))
    (set-frame-parameter
     nil 'persp--last
     (let* ((persp-sort 'access)
            (names (persp-names))
            (last (nth 1 names)))
       (when last
         (gethash last (perspectives-hash))))))
  (when (or (not (persp-curr)) (equal name (persp-current-name)))
    ;; Don't let persp-last get set to the deleted persp.
    (persp-let-frame-parameters ((persp--last (persp-last)))
      (persp-switch (persp-find-some)))))
```

Let me know if it works. Even if it does, though, IMO it's a bug in treemacs-perspective. It expects `treemacs--on-scope-kill` to be useable directly as a hook, but `persp-killed-hook` never advertised an interface with a parameter. It's a simple fix on the treemacs-perspective side to wrap `treemacs--on-scope-kill` with `(lambda () (treemacs--on-scope-kill persp-curr))` (or better yet, a dedicated named function).

**Comment by Randy1Burrell** [comment]
Yes this worked thanks.

I thinks it's a treemacs-perspective issue too.

**Comment by gcv** [comment]
Great. I want to open a Treemacs PR to sort this out. Here's my patch: https://github.com/gcv/treemacs/commit/c536ec2e24594c311ffab1a0fdfc9f1af6f848a3

Could you please give it a quick spin before I open the pull request? It seems to work for me, but I never used treemacs-perspective before (though I sometimes use just treemacs by itself) so it'd be good to have you look over it. You'll have to revert the definition of `persp-kill` from the one I posted above to the one Perspective ships with.

**Comment by Randy1Burrell** [comment]
@gcv just tested it and it seems to be working great.

**Comment by gcv** [comment]
@Randy1Burrell: This bug should now be fixed in treemacs.

**Comment by Randy1Burrell** [comment]
@gcv great, thank you.

**Comment by Randy1Burrell** [comment]
Closing!!
