### ISSUE TITLE
Perpective causes Emacs to freeze

### ISSUE THREAD

**Issue by Randy1Burrell** [nex3/perspective-el#147]
When using tramp to open remote files os using ssh-mode, switching between buffers using `persp-ivy-switch-buffer` or `persp-counsel-switch-buffer` causes Emacs to freeze. This is especially true when you have more than one remote buffer open.

I could be wrong but `persp-ivy-switch-buffer` and `persp-counsel-switch-buffer` seem to be trying to build a graphical view of each buffer so that it displays previews but can't seem to handle remote files. Maybe a failsafe would be good for when someone has a remote file(s) open while in persp-mode.

## Steps to reproduce
1. Go into persp-mode
2. Open remote files using Tramp/ssh buffer using ssh-mode
3. Do some editing
4. Try to switch buffer using either function

Calling either function freezes Emacs, but if I use `counsel-switch-buffer` or `ivy-switch-buffer` everything is fine. I could go ahead and ignore this bug but my switch-buffer keys are already bound to `persp-[counsel|ivy]-switch-buffer` functions, so this is kind of a bummer.

**Comment by gcv** [comment]
I can't reproduce this problem, though I don't have any handy remote hosts to ssh into and just tried ssh to localhost (which might bypass whatever you're running into). It's certainly possible that the way Perspective calls into Ivy is suboptimal for remote buffers.

When you say these functions freeze Emacs, do you mean beyond recovery with `C-g` or similar?

Do you use ivy-rich or another metadata system which might slow down over ssh?

Maybe you could try calling the slow functions with `profiler-start` and `profiler-report` to look for obvious culprits? If you're unfamiliar with the Emacs profiler, this (extremely long) article about Emacs surfaced recently, and its first part contains a pretty decent profiling tutorial: https://www.murilopereira.com/how-to-open-a-file-in-emacs/

**Comment by Randy1Burrell** [comment]
Yes when I say freeze, I mean freeze to the point where I have to kill Emacs and start it again. `C-g` or no other keys will work. Yes, I do use ivy-rich.

I will look into profiling.

**Comment by gcv** [comment]
Does this problem still happen if you disable ivy-rich? I’m wondering if it’s being too clever in combination with how Perspective uses the Ivy API. The profiler probably won’t work since it sounds like the main Emacs thread locks up (yikes).

If you use a Mac, you can do a bit of analysis using DTrace (access through Activity Monitor, examine the process, and there should be a way to sample it). Usually, when the Emacs thread locks up, you can find some tell-tale functions on the stack. On Linux, maybe `strace` will help. On Windows, not sure how to debug.

**Comment by gcv** [comment]
Please reopen if this is still a problem.
