### ISSUE TITLE
persp-counsel-switch-buffer open in other window

### ISSUE THREAD

**Issue by farynaio** [nex3/perspective-el#148]
I look for a way to have variant of persp-counsel-switch-buffer that works similar to counsel-switch-buffer-other-window - open in other window.

What is the easy way to achieve that?

**Comment by gcv** [comment]
I think passing `ivy--switch-buffer-other-window-action` as the `:action` to `ivy-read` [right here](https://github.com/nex3/perspective-el/blob/d46082ca2adb8df3f6a7a422cff4af095878c2b6/perspective.el#L1270) will do the trick, but it’ll take a bit of refactoring to make it fit cleanly with the rest of the code. PRs always welcome, or you can just copy-paste the existing code and add the extra functionality in your own configuration. 😁 If you don’t feel comfortable enough with Elisp for either approach, I can try to find some time in a few days.

**Comment by farynaio** [comment]
> I think passing `ivy--switch-buffer-other-window-action` as the `:action` to `ivy-read` [right here](https://github.com/nex3/perspective-el/blob/d46082ca2adb8df3f6a7a422cff4af095878c2b6/perspective.el#L1270) will do the trick, but it’ll take a bit of refactoring to make it fit cleanly with the rest of the code. PRs always welcome, or you can just copy-paste the existing code and add the extra functionality in your own configuration. 😁 If you don’t feel comfortable enough with Elisp for either approach, I can try to find some time in a few days.

Thanks. I put together a function - it's a Frankenstein made of `persp--switch-buffer-ivy-counsel-helper` and `persp-ivy-switch-buffer` - below but something is wrong with that. The amount of options from ivy is limited to current buffer.

```lisp
  (defun my/persp-counsel-switch-buffer-other (arg)
    (interactive "P")
    (apply #'ivy-read
      (append
        (list
          (format "Switch to buffer other window (%s): " (persp-current-name))
          (cl-remove-if #'null (mapcar #'buffer-name
                                 ;; buffer-list is ordered by access time
                                 ;; seq-intersection keeps the order
                                 (seq-intersection (buffer-list)
                                   (persp-current-buffers))))
          :preselect (buffer-name (persp-other-buffer (current-buffer)))
          :keymap ivy-switch-buffer-map
          :caller #'ivy-switch-buffer
          :action #'ivy--switch-buffer-other-window-action
          :matcher #'ivy--switch-buffer-matcher)
        )))
```
