### ISSUE TITLE
Variable display-buffer-reuse-frames in the README is obsolete

### ISSUE THREAD

**Issue by RJSent** [nex3/perspective-el#149]
In the "Some Musings on Emacs Windows Layouts" section of the README, there is sample code meant to adjust default behavior in Emacs. As of Emacs 24.3, `display-buffer-reuse-frames` is obsolete and would not have an effect.

The code in question
```emacs-lisp
(setq display-buffer-alist
      '((".*" (display-buffer-reuse-window display-buffer-same-window))))

(setq display-buffer-reuse-frames t)         ; reuse windows in other frames
(setq even-window-sizes nil)                 ; display-buffer: avoid resizing
```
The help page for `display-buffer-reuse-frames` suggests using a `reusable-frames` alist entry in `display-buffer-alist` instead.

**Comment by gcv** [comment]
Thanks! Example updated in https://github.com/nex3/perspective-el/commit/697d95f24e055eb9725781d179d7db63d6afd2b5.
