### ISSUE TITLE
can access buffer that is part of another perspective

### ISSUE THREAD

**Issue by zwwv** [nex3/perspective-el#153]
Say I create a perspective `a` with buffer `file1.cpp`. Then I create another perspective `b`.
While inside perspective `b` I use switch buffer (c-x b) and type `f` in min-buffer and press tab button it auto completes to
`file1.cpp` even though buffer `file1.cpp` is part of perspective `a`. Is there a way to avoid this?

**Comment by gcv** [comment]
The basic `switch-to-buffer` function bound to `C-x b` is, indeed, not Perspective-aware. I'll accept a PR to fix this (please follow guidelines outlined in https://github.com/nex3/perspective-el/pull/152). However, many other popular buffer switchers are fully Perspective-aware, see the [Buffer switchers](https://github.com/nex3/perspective-el/#buffer-switchers) section of the README. Would one of those work for you? In particular `ido-switch-buffer` is both built-in and fairly similar (and IMO superior) to `switch-to-buffer`.

**Comment by gcv** [comment]
Please reopen if the suggested solution does not work for you.
