### ISSUE TITLE
feature-request: persp-only

### ISSUE THREAD

**Issue by paulophagula** [nex3/perspective-el#156]
I'd like to request adding a feature that allows killing all other "persps" but the current (`persp-only`).

**Comment by gcv** [comment]
Done. `persp-kill-others`. I didn't give it a default keybinding, since it's a dangerous operation, even with the confirmation prompt. Commit 2ff458a. It's in MELPA now.

**Comment by paulophagula** [comment]
What? Already? 😮  ... Thanks for the very fast response 🙇🏿🙌🏿
