### ISSUE TITLE
Perspective operations in recursive minibuffers not supported

### ISSUE THREAD

**Issue by dpassen** [nex3/perspective-el#167]
Since a recent change, I've seen an increasing number of 
```
(user-error "Perspective operations in recursive minibuffers not supported")
```

Two areas I frequently see this error are:
```
Error running timer ‘mac-setup-help-topics’: (user-error "Perspective operations in recursive minibuffers not supported")
Error in ‘cider-repl--state-handler’: (user-error Perspective operations in recursive minibuffers not supported)
```

perspective 20211023.1507
emacs-27.2 https://github.com/railwaycat/homebrew-emacsmacport
macOS Monterey (12.0.1)

**Comment by gcv** [comment]
I pushed an attempted fix in commit 520b038. It'll hit MELPA in a couple of hours. It seems to be compatible with #163, but might help with this bug. I just ran into it today myself: it seems that switching perspectives while a (background) timer is running makes it look like a recursive minibuffer session is in progress. I don't know why. Maybe this fix will make the problem go away, maybe not. Please let me know.

**Comment by ibytao** [comment]
no fix

**Comment by deejayem** [comment]
I wonder if the "Perspective operations in recursive minibuffers not supported" error is just a symptom of something else that has broken. After commenting out the new check that was added, I'm now seeing this error:

`Specified root is not an ancestor of specified window`, and also seeing emacs crash.

The problems went away when I removed perspective from my config. After re-enabling it, I didn't see any probelms again, until I told consult to use this function to determining project roots:
```
  (defun persp-current-project-root ()
    "Return the current project root, falling back to finding it using the perpsective"
    (if-let (project (project-current))
        (project-root project)
      (when-let (persp (persp-name (persp-curr)))
        (car (seq-filter (lambda (pr) (string-match-p persp pr)) (project-known-project-roots))))))
```
But I'm not sure why, as most of the time it should never get to the when-let (and the project part by itself works fine).

Apologies if this unrelated/just noise, but both issues started after updating to the latest release.

**Comment by gcv** [comment]
@deejayem: Since you seem to run into the error fairly frequently, would you mind helping narrow down the commit when it was introduced? I assume you're currently using the latest in MELPA. Could you try one of the tagged releases?

- [version 2.17](https://github.com/nex3/perspective-el/tree/2.17)
- if 2.17 is still broken, then maybe [2.16](https://github.com/nex3/perspective-el/tree/2.16)

**Comment by deejayem** [comment]
2.17 works fine. I've narrowed it down to commit bf0fce1f - it works fine with the commit before that, but with that commit I get the errors.

**Comment by gcv** [comment]
Thank you @deejayem!

@mehw — we missed this problem while testing #165. It seems related to timers, or at least the reports here suggest so. The one time I saw it myself also had something to do with `git-auto-commit-mode`, which also runs timers.

While looking into #163, I found that `persp-reset-windows` seems to have caused problems with recursive minibuffers. Is it possible that timers create a situation in which interactive commands runs in an unexpected window context? Then `(delete-other-windows)` or `(delete-window)` in `persp-reset-windows` get called while `(selected-buffer)` is the same as `(minibuffer-window)`.

I'm not sure if that means that a trivial fix is to do something like

```elisp
(delete-other-windows (when (eq (minibuffer-window) (selected-window)) (previous-window (minibuffer-window))))
```

and something similar in the call to `delete-window` in `persp-reset-windows`.

There might be some deeper breakage, though. What do you think?

**Comment by gcv** [comment]
I just pushed a couple of commits that should help work around this problem.

@deejayem, @ibytao, @dpassen: could you please grab 3e4efab, which should be in MELPA in a couple of hours, and see if things improve.

**Comment by deejayem** [comment]
It seems to be working fine for me now, thank you.

**Comment by dpassen** [comment]
Fixed for me, as well!

**Comment by mehw** [comment]
> @mehw — we missed this problem while testing #165. It seems related to timers, or at least the reports here suggest so. The one time I saw it myself also had something to do with `git-auto-commit-mode`, which also runs timers.
> 
> There might be some deeper breakage, though. What do you think?

Hi @gcv, I'm reading your messages right now... Thanks for the quick fix, I'll look into the code this night ;)
