### ISSUE TITLE
Marginalia annotation not working with `persp-switch-to-buffer*`

### ISSUE THREAD

**Issue by ahmed-shariff** [nex3/perspective-el#169]
I am using selectrum for completion. Since perspective generates a list as a candidate list for `completing-read`, when using `persp-switch-to-buffer*` marginalia's annotations don't work.  According to https://github.com/minad/marginalia/issues/48 : 

> buffer completion category the problem should be fixed and you will get the usual marginalia buffer annotations which work for switch-to-buffer!

Though I have not clue what this means.

**Comment by gcv** [comment]
I gave it a shot. Can you try the https://github.com/nex3/perspective-el/tree/add-metadata-to-persp-switcher branch?

**Comment by ahmed-shariff** [comment]
sweet, thanx alot. This seems to work. I'll open a new issue if I run into anything else related to this.

**Comment by gcv** [comment]
Patch merged into master and should reach MELPA in a couple of hours.

**Comment by ahmed-shariff** [comment]
For reference for anyone looking for a solution with [consult ](https://github.com/minad/consult) 

``` emacs-lisp
     (consult-customize consult--source-buffer :hidden t :default nil)
   
     (defvar consult--source-perspective
       (list :name     "Perspective"
             :narrow   ?s
             :category 'buffer
             :state    #'consult--buffer-state
             :default  t
             :items    #'persp-get-buffer-names))
   
     (push consult--source-perspective consult-buffer-sources)
```
