### ISSUE TITLE
[feature request] - Option to not save modes for buffers

### ISSUE THREAD

**Issue by ZelCloud** [nex3/perspective-el#181]
I've been using persp-state-save and persp-state-load for a while now, and it works great. Except for one case, if there's some kind of issue or bug with a mode or elsip command it seems to be persisted into the persp-state-save and loaded up the following time. Generally one of the perspectives will also lose its named title and get a random string of numbers. So would it be possible to save the buffers and spaces but not included the running modes of said buffer?

**Comment by gcv** [comment]
`persp-state-save` avoids saving anything it cannot reliably restore. This includes all kinds of buffers, like shells, which do not have an associated file. It sounds like you ran into a mode that those heuristics don't catch. What mode have you run into with this problem? Can you help me reproduce it?
