### ISSUE TITLE
Can't setup perspective layout at startup

### ISSUE THREAD

**Issue by JuanPabloMF** [nex3/perspective-el#183]
Perspective works fine for me with a simple configuration like:

```
  (use-package perspective
      :custom
      (persp-mode-prefix-key (kbd "C-c x"))
      :config
      (persp-mode)
      )
```

The error arises when I try to create from my init file a new perspective with a given window and buffer layout:

```
  (defun my/startup-window-layout ()
    (split-window-horizontally)
    (other-window 1)
    (split-window-below)
    (other-window 2)
    )

  (defun my/config-startup-perspective ()
    (persp-switch "project")
    (my/startup-window-layout)
    (switch-to-buffer "*dashboard*")
    (other-window 1)
    (shell (generate-new-buffer-name "*shell*"))
    (other-window 1)
    (switch-to-buffer "*scratch*")
    )

  (use-package perspective
      :demand t
      :custom
      (persp-mode-prefix-key (kbd "C-c x"))
      :config
      (persp-mode)
      (my/config-startup-perspective)
      )
```

With this config the "project" perspective is not created, only the buffers are visible but not attached to the main perspective and the project perspective as I mentioned doesn't exist.

I have tried a few things:

- without :demand t the perspective gets created but the buffers and window layout only appear after running persp-counsel-switch-buffer.
- trying to run the my/config-startup-perspective with the persp-mode-hook gives the same result that with :demand t.

Also for some reason the function seems to be executed twice (I get two shell buffers created), meaning that persp-mode would be activated twice also.

**Comment by gcv** [comment]
Try using `:init` instead of `:config` in your `use-package` forms. I recently changed the documentation to do that to avoid all kinds of subtle lazy loading problems, which is what I suspect is happening here. Also, maybe change to `(persp-mode 1)`. Maybe I should change the README to do that, too.

For your use case, maybe look into `persp-state-save` and `persp-state-load`? You can set everything up exactly the way you want, save to a well-known file (instead of the default), and load from it.

**Comment by JuanPabloMF** [comment]
Changed to init, and I don't get anymore the double shell buffer, thus I suppose that it is loading just one time.

What I'm still not able to do is to run from elisp the layout function `my/config-startup-perspective`. I tried to use the persp-mode-hook, after-init-hook, emacs-startup-hook, and also using from use-package the :demand and :config keywords.

On the other hand, I'm able to run interactively with M-x the function once everything is loaded.

Is there a way to run this from elisp with a hook or :config?

**Comment by gcv** [comment]
The following works for me using `emacs -Q -l /path/to/perspective-autoloads.el -l /path/to/use-package-autoloads.el`:

```elisp
(defun my/startup-window-layout ()
  (split-window-horizontally)
  (other-window 1)
  (split-window-below)
  (other-window 2)
  )

(defun my/config-startup-perspective ()
  (persp-switch "project")
  (my/startup-window-layout)
  (switch-to-buffer "*dashboard*")
  (other-window 1)
  (shell (generate-new-buffer-name "*shell*"))
  (other-window 1)
  (switch-to-buffer "*scratch*")
  )

(use-package perspective
  :custom
  (persp-mode-prefix-key (kbd "C-c x"))
  :init
  (persp-mode 1)
  (my/config-startup-perspective)
  )
```

It's the same thing you posted originally, except `:config` is replaced with `:init`. Note that you switch to `*scratch*` in `my/config-startup-perspective` rather than `*scratch* (project)`, but I assume that's intentional.

Please try this with `emacs -Q` and similar `-l` flags to mine.

**Comment by JuanPabloMF** [comment]
It works! 

I had tried this kind of setups and they were not working for me. After a bit of tinkering I think I found the problem:

- Opening from shell works with `emacs -Q -l` and also `emacs`.
- Opening from app icon in favorite apps bar doesn't work.

The app icon in favorite bar was emacsclient.desktop. There is also another app icon in emacs folder /usr/local/share/emacs/28.1.50/etc/ called emacs.desktop.

- emacsclient.desktop executes the following: `sh -c "if [ -n \\"\\$*\\" ]; then exec emacsclient --alternate-editor= --display=\\"\\$DISPLAY\\" \\"\\$@\\"; else exec emacsclient --alternate-editor= --create-frame; fi" placeholder %F`
- emacs.desktop simply executes: `emacs %F`

Don't really know if one of the flags or the command `emacsclient` is breaking the elisp code execution.

Thanks for the help! (just changing .desktop file to fix my problem)
