### ISSUE TITLE
Load last perspective session on Emacs startup?

### ISSUE THREAD

**Issue by tr37ion** [nex3/perspective-el#19]
Hi, this is a great Emacs script. Yet I have a question:

_How can I keep my persp setup persistant even if I restart Emacs? (autoload on startup)_

I searched the source for a solution, but couldn't find it. It would be really nice, if you could help with this. I can't imagine that I have to setup my persp tags on every restart of Emacs.

**Comment by fvaresi** [comment]
I was just trying to achieve something similar by using [desktop-save-mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Saving-Emacs-Sessions.html), but it doesn't work out-of-the-box.

I guess a little extra work is required to restore perspective state, will look into it when I find some time.

**Comment by seagle0128** [comment]
I switch to use persp-mode, which provides saving and restoring features.
visit https://github.com/Bad-ptr/persp-mode.el.

**Comment by pdex** [comment]
I looked into `persp-mode`, but it doesn't play well with projectile (which is part of the reason I'm using perspectives). I'm not interested in using `revive` since `desktop-save-mode` can restore window configurations. 

So I threw together some functionality to save/restore the buffers and perspective names using `desktop-save-mode`. I may spend some time figuring out how to save/restore everything else in the persp struct, but this does 99% of what I need.

```
  (defun perspectives-buffer-name-p (buffer)
    (if (and buffer
	     (buffer-name buffer)
	     (not (string-prefix-p "*" (buffer-name buffer)))
	     (not (string-suffix-p "*" (buffer-name buffer))))
	t
      nil))

  (defun perspectives-hash-filter (current filtered parameters saving)
    (let ((value (cdr current))
	  (result ())
	  (keys (hash-table-keys (cdr current))))
      ;; for every perspective...
      (dolist (key keys)
	(let ((persp (gethash key value)))
	  ;; that isn't killed...
	  (if (not (persp-killed persp))
	      (add-to-list
	       'result
	       (cons key
		     ;; save the list of buffers
		     (list (cons "buffers"
		     (list
		      (mapcar 'buffer-name (seq-filter 'perspectives-buffer-name-p (persp-buffers persp)))))))))))
    ;; return a different variable name so perspectives doesn't clobber it
    (cons 'perspectives-hash-serialized result)))

  ;; serialize perspectives hash
  (add-to-list 'frameset-filter-alist '(perspectives-hash . perspectives-hash-filter))
  ;; don't serialize anything else
  (add-to-list 'frameset-filter-alist '(persp-modestring . :never))
  (add-to-list 'frameset-filter-alist '(persp-recursive . :never))
  (add-to-list 'frameset-filter-alist '(persp-last . :never))
  (add-to-list 'frameset-filter-alist '(persp-curr . :never))

  (defun perspectives-restore-state ()
    (dolist (frame (frame-list))
      ;; get the serialized state off of the frame
      (let ((state (frame-parameter frame 'perspectives-hash-serialized)))
	(if state (progn
		    (message "Found state, attempting restore")
		    ;; delete it so we don't end up in a loop
		    (set-frame-parameter frame 'perspectives-hash-serialized nil)
		    (with-selected-frame frame
		      (dolist (elem state)
			;; recreate the perspective
			(with-perspective (car elem)
			  (dolist (buffer-name (car (cdr (assoc "buffers" (cdr elem)))))
			    ;; add the buffer back to the perspective
			    (persp-add-buffer buffer-name)
			    )))
		      ))
	  (message "No state found")
	  )
	)))

  (add-hook 'desktop-after-read-hook 'perspectives-restore-state)
```

**Comment by gcv** [comment]
I took a shot at adding durability support. Please take a look: https://github.com/nex3/perspective-el/pull/80 (or my fork, https://github.com/gcv/perspective-el).

**Comment by gcv** [comment]
This feature is now available as `persp-state-save` and `persp-state-load`.

**Comment by gcv** [comment]
Please see https://github.com/nex3/perspective-el/issues/200.

**Comment by alphapapa** [comment]
FYI, you may find this new package interesting.  It doesn't do exactly what `perspective` does, but it's similar: https://github.com/alphapapa/activities.el

**Comment by gcv** [comment]
Hi @alphapapa! I took a look at Activities. It looks really promising, and it's really nice that it's built on modern Emacs foundations. Perspective is certainly showing its age (first commit in March 2008), and pretty much all open long-lasting tickets result from it. I'll definitely try Activities as a daily driver once `switch-to-buffer` filtering arrives (it's something in Perspective I can't live without).

PS: Small correction to the Activities README (where it says "To date, only Burly and Bufler seem to offer the ability to restore one across Emacs sessions"): Perspective _does_ allow saving and loading state, so perspectives can be restored in a new Emacs session. The implementation is less elegant than the bookmarks approach you chose, and probably more limited, but it works well enough.

**Comment by seagle0128** [comment]
Another great alternative is [tabspaces](https://github.com/mclear-tools/tabspaces), which is built on the built-in packages: tabbar and project (27.1+). It's simple but flexible.

>Tabspaces leverages [tab-bar.el](https://github.com/emacs-mirror/emacs/blob/master/lisp/tab-bar.el) and [project.el](https://github.com/emacs-mirror/emacs/blob/master/lisp/progmodes/project.el) (both built into emacs 27+) to create buffer-isolated workspaces (or “tabspaces”) that also integrate with your version-controlled projects. It should work with emacs 27+. It is tested to work with a single frame workflow, but should work with multiple frames as well.

**Comment by alphapapa** [comment]
> I'll definitely try Activities as a daily driver once `switch-to-buffer` filtering arrives (it's something in Perspective I can't live without).

Understood.  Well, I just pushed `activities-switch-buffer`.  Please see https://github.com/alphapapa/activities.el/issues/43#issuecomment-1970643750 and let me know what you think.

**Comment by alphapapa** [comment]
> PS: Small correction to the Activities README (where it says "To date, only Burly and Bufler seem to offer the ability to restore one across Emacs sessions"): Perspective _does_ allow saving and loading state, so perspectives can be restored in a new Emacs session. The implementation is less elegant than the bookmarks approach you chose, and probably more limited, but it works well enough.

Thanks.  I've updated it to mention non-file-backed buffers, which seems to be the key distinction.  https://github.com/alphapapa/activities.el/commit/80e76f29246c11205d681ee6b61fac1c6c10f106
