### ISSUE TITLE
`C-x 5 2 ` different behaviour when running perspective with daemon

### ISSUE THREAD

**Issue by wolf-coder** [nex3/perspective-el#193]
- (persp-mode enabled) Without running a daemon, `C-x 5 2` behave normally (_It creates a new frame and switch to it_).
- (persp-mode enabled) When running a daemon , it opens a new  frame with a *Scratch* buffer.
- (persp-mode enabled) Without daemon, `C-x 5 2`, behave as expected.

_ Clearly, there is a conflict between Perspecive and daemon for `C-x 5 2`.
_ Any guidance to fix this please?

> - emacs version: 27.1
> - perspective version: Version: 2.18
> - emacsclient command: `emacsclient -c -a "emacs" %F`

**Comment by gcv** [comment]
I tried this with Emacs 27.2, Mac port, GUI version. Whether or not the Emacs server process is running (`M-x server-start`), and whether or not Perspective is enabled, <kbd>C-x 5 2</kbd> creates a new frame with the current buffer opened in it. I just used `emacsclient` to open files without any flags. Maybe I don't understand what you mean by `running a daemon`?

**Comment by gcv** [comment]
Please reopen if this is still a problem.
