### ISSUE TITLE
Issue with using ediff and perspective 

### ISSUE THREAD

**Issue by celdorwow** [nex3/perspective-el#196]
I have noticed an issue with `ediff`. When `perspective` is active, that is Emacs starts up with the default `[main]`, every use of `ediff` kind of locks the perspective it is issued from.

This is how I reproduce the issue:
* Start Emacs with active `perspective`--`[main]` should be the only perspective and active
* Switch to a new perspective, e.g. `test`, a new perspective `[test]` is active 
* Activate `ediff`--run `ediff (ediff-files)` on two example files
* Quit `ediff`
* Now the `[main]` perspective should disappear
* `[test]` is kind of locked.

From now on activities related to `[test]` should causes error: `Using killed perspective 'test'`.

Also for instance, If I create a new perspective, say `aaa`, the [main] is available again. However, any attempt to:
* switching to [test]
* killing any buffer in [test] or
* even killing the perspective `[test]` itself causes: `Using killed perspective 'test'` error.

**Comment by gcv** [comment]
I followed your sequence of steps and cannot reproduce this problem. Ediff works fine for me. Are you using a recent version of Perspective? Several people contributed a bunch of work a year or two ago to eliminate “Using killed perspective” errors. Have you tried this with a minimal configuration (i.e. with just Perspective installed)?

**Comment by celdorwow** [comment]
> Are you using a recent version of Perspective?

I believe I am. I run `list-packages` followed `U` to update anything Emacs asks for, daily. Emacs version is 28.2 and installed `perspective` version is  20220921.346

> Have you tried this with a minimal configuration

No, I haven't. To be honest I don't know how to do that effectively without corrupting my current settings. I have been using Emacs for some time but still learning it.

BTW this is the list of other packages I have installed:

```
  all-the-icons                  20220929.2303  installed             A library for inserting Developer icons
  atom-dark-theme                20220114.1902  installed             An Emacs port of the Atom Dark theme from Atom.io.
  atom-one-dark-theme            20210128.1640  installed             Atom One Dark color theme
  auctex                         13.1.9         installed             Integrated environment for *TeX*
  counsel                        20221015.936   installed             Various completion functions using Ivy
  csv-mode                       1.22           installed             Major mode for editing comma/char separated values
  doom-modeline                  20230201.1701  installed             A minimal and modern mode-line
  evil                           20230207.1932  installed             Extensible Vi layer for Emacs.
  grip-mode                      20230206.323   installed             Instant GitHub-flavored Markdown/Org preview using grip.
  ivy                            20220926.1250  installed             Incremental Vertical completYon
  ivy-prescient                  20221216.112   installed             prescient.el + Ivy
  ivy-rich                       20210409.931   installed             More friendly display transformer for ivy
  multiple-cursors               20230113.835   installed             Multiple cursors for Emacs.
  org-bullets                    20200317.1740  installed             Show bullets in org-mode as UTF-8 characters
  org-roam                       20221231.2122  installed             A database abstraction layer for Org-mode
  pdf-tools                      20230117.632   installed             Support library for PDF documents
  perspective                    20220921.346   installed             switch between named "perspectives" of the editor
  projectile                     20221122.2032  installed             Manage and navigate projects in Emacs easily
  rainbow-delimiters             20210515.1254  installed             Highlight brackets according to their depth
  tablist                        20200427.2205  installed             Extended tabulated-list-mode
  use-package                    20230203.2004  installed             A configuration macro for simplifying your .emacs
  visual-regexp                  20210502.2019  installed             A regexp/replace command for Emacs with interactive visual feedback
  which-key                      20220811.1616  installed             Display available keybindings in popup
```

**Comment by gcv** [comment]
That's so strange. Can you please start Emacs like this;

```
emacs -Q -l /path/to/emacs/packages/perspective-20220921.346/perspective-autoloads.el
```
You can figure out the path by evaluating `package-user-dir` (using `M-:`).

Then paste this code into `*scratch*`:
```
(persp-mode 1)
(persp-switch "test")
(ediff-files "~/1.txt" "~/2.txt")
```
Run `M-x eval-buffer`. Ignore warnings about `persp-mode-prefix-key`.

Then quit ediff (`q`) and run `M-x persp-switch`. `main` should be available.

This works perfectly for me in Emacs 28.2 on Linux.

**Comment by celdorwow** [comment]
Hi again,

Thanks for helping with me with this. Unfortunately, the same issue is occurring. The `[main]` disappears once I leave `ediff`. It is back if I create a new perspective, say `[aaa]`. However, trying to get to `[test]` issues "Using killed perspective 'test'".

I did not think of it before but perhaps it is time to say how I run Emacs. So my system is `Linux Ubuntu-Home 5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux` via `uname -a` and I installed Emacs using `snap`; `snap  --version` gives me:

```
snap    2.58+20.04
snapd   2.58+20.04
series  16
ubuntu  20.04
kernel  5.15.0-58-generic
```

`snap list`:

```
Name           Version     Rev    Tracking         Publisher       Notes
...
emacs          28.2        1808   latest/stable    alexmurray*     classic
...
```

**Comment by gcv** [comment]
After watching your screencast, I have an idea. Try this:

```
(customize-set-variable 'ediff-window-setup-function 'ediff-setup-windows-plain)
```

This forces Ediff to use the same frame for its control panel as the frame from which it's launched (which I consider cleaner anyway). Because Perspective state is tightly bound to originating frames, the separate Ediff control panel may have confused it. Try your use case again and see what happens (you probably don't need the `-Q` incantation and can just test with your normal configuration).

**Comment by celdorwow** [comment]
Yes, this works. Also, I like it does not open a new window but displays its menu in the echo area.

Thanks
