### ISSUE TITLE
Feature request: Add `perspective-kill-other-buffers`

### ISSUE THREAD

**Issue by PauloPhagula** [nex3/perspective-el#203]
We have `persp-kill-buffer*` which replaces `kill-buffer` with a perspective aware version.

When we have too many buffers open it's common to want to kill all other buffers but the current one, to free some state. Usually I resort to `crux-kill-other-buffers` from the [crux](https://github.com/bbatsov/crux) package.

I'd like to request that you please add the equivalent for perspective, so I can kill all other buffers from the current perspective but the current buffer?

Thanks

**Comment by gcv** [comment]
Added in ec48cb3bdda8c5ea12da89a12aa925ed1905a0b7, which should be in MELPA in a couple of hours. Please try it and let me know how it works for you.

**Comment by gcv** [comment]
Please reopen this ticket if necessary.

**Comment by PauloPhagula** [comment]
Finally go to test it. And it works just fine. Thanks a lot @gcv
