### ISSUE TITLE
function to add buffer to persp other than current persp

### ISSUE THREAD

**Issue by titibandit** [nex3/perspective-el#205]
Actually to address the problem mentioned in issue #50 (add erc buffers to the perspective), I was trying to modify my erc configuration accordingly.
As noted there, the `persp-add-buffer` need to be called.
This adds a given buffer to the current perspective.

As erc creates the buffer only the a connection to a channel is established, I might have already moved perspective during the time needed to establish the connection, so the current perspective is not the one I want to add that buffer to anymore.
It seems there is no function like (persp-add-buffer persp-name), where one can specify to which perspective a buffer need to be added to. Or am I missing it?
Maybe it would make sense for these cases to have the function (persp-add-buffer &optional persp-name)?

**Comment by gcv** [comment]
We have a `with-perspective` macro. Would that work for you?

**Comment by titibandit** [comment]
This absolutely works. Thanks.
That makes the integration with the erc irc client pretty neat actually.
