### ISSUE TITLE
Avoid helm dependency?

### ISSUE THREAD

**Issue by mok0** [nex3/perspective-el#209]
I am using the modern Emacs vertico/counsel/marginalia frameworks. However, when I install `perspective.el`, it pulls in `helm` as a dependency. Any way I can avoid it?

**Comment by gcv** [comment]
The activation code does look it could do a better job of keeping Helm integration out of the way. I'm surprised it's getting installed automatically though. It's not listed as a dependency. How do you install Perspective?

**Comment by mok0** [comment]
I analyzed further where helm comes from, and it may not be `perspective-el` after all. It is installed by the `emacs-gooodies ` package on my Debian system and probably loaded by default somehow.
