### ISSUE TITLE
ido-switch-buffer does not honor ido-ignore-buffers 

### ISSUE THREAD

**Issue by glucas** [nex3/perspective-el#28]
When persp-mode is enabled any ignored buffers become visible. Doing an 'ido-switch-buffer' shows buffers like *Minibuf-x* and *Echo Area x*.

Ideally it would be possible to customize (and toggle) ido-ignore-buffers with persp-mode enabled.

**Comment by nex3** [comment]
I think #47 should fix this, but I don't use ido so I don't know for sure. Can you verify?

**Comment by glucas** [comment]
Yes -- did some quick testing and looks good. Thanks!
