### ISSUE TITLE
Dies on load

### ISSUE THREAD

**Issue by zenspider** [nex3/perspective-el#40]
Disabled elscreen, restarted emacs, ran `persp-mode` manually and got the following:

```
Debugger entered--Lisp error: (void-variable +)
  autoload-do-load((autoload "perspective" "Toggle perspective mode.\nWhen active, keeps track of multiple 'perspectives',\nnamed collections of buffers and window configurations.\n\n(fn &optional ARG)" t nil) persp-mode)
  command-execute(persp-mode record)
  execute-extended-command(nil "persp-mode")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
```

**Comment by nex3** [comment]
I don't know how to do anything with melpa, but I'm about to do a new release with a new version number and hopefully that'll help.

**Comment by zenspider** [comment]
_should_ just be a matter of pushing to github at this point. The "version" on melpa matches your last commit time (jan 5).
