### ISSUE TITLE
Feature request: check whether Perspective Mode is enabled.

### ISSUE THREAD

**Issue by fehmud** [nex3/perspective-el#48]
When an user calls a Perspective command while Perspective Mode is not enabled, the call could fail with a cryptic error.  For instance, `persp-switch` fails with `let*: Wrong type argument: hash-table-p, nil`. A more user-friendly approach would be to alert the user, for instance by adding this snippet of code at the beginning of each command:

```
(unless (bound-and-true-p persp-mode)
  (error "Perspective Mode is not enabled."))
```

Or even:

```
(unless persp-mode
  (persp-mode 1))
```

Thanks for your attention.

**Comment by egarrulo** [comment]
Oops! I meant:

    (unless (bound-and-true-p persp-mode)
      (persp-mode 1))

**Comment by magnetophon** [comment]
Recent Emacs convert here.
Can confirm!

I imagine the downside would be that these commands become slightly sower?

**Comment by zenspider** [comment]
Defined and adding `(persp-mode-guard)` to `persp-switch`.

One of the amazing things is that this isn't just an infinite loop, but you can't escape it even with `top-level`.

**Comment by zenspider** [comment]
Closing this...
