### ISSUE TITLE
perspective hides buffers created by erc-autojoin-channels-alist

### ISSUE THREAD

**Issue by 4DA** [nex3/perspective-el#50]
Hi. When i turn on perspective via _(persp-mode)_ all buffers created in background by erc from _erc-autojoin-channels-alist_ **are not visible** in buffers list (M-x list-buffers, C-x C-b)

Thanks.

How to reproduce:

```
(setq debug-on-error t)

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)

(package-initialize)

(require 'perspective)
(persp-mode)

(setq erc-join-buffer (quote bury))
(setq erc-autojoin-mode t)
(setq erc-autojoin-channels-alist (list (list "freenode" "#emacs")))

(erc :server "irc.freenode.net" :nick "testtest")
```

**Comment by gcv** [comment]
The solution is to have erc call `persp-add-buffer` in a hook after it creates a buffer in the background.

Supporting this explicitly for other Emacs software is out of scope for Perspective, and is easy enough to do. I will, however, gladly accept a PR for documenting the procedure for popular packages.
