### ISSUE TITLE
Confusing package names

### ISSUE THREAD

**Issue by alphapapa** [nex3/perspective-el#53]
I see these packages available in Emacs:
```
  persp-mode       h 20151017… available  melpa       46  "perspectives" shared among frames + save/load - bugs. 
  perspective      h 20151016… available  melpa      211  switch between named "perspectives" of the editor
```
Your readme says to install `perspective` but to activate `persp-mode`.

What do I do? D:

**Comment by nex3** [comment]
The package named "persp-mode" is Bad-ptr/persp-mode.el, a fork of this package with a confusingly similar but distinct name. We're theoretically planning to re-merge them, but neither of us has the time to devote to it at the moment.

For now, if you want to use this repo's package, use the package named "perspective".

**Comment by alphapapa** [comment]
Thanks.
