### ISSUE TITLE
Feature request - iBuffer support

### ISSUE THREAD

**Issue by voipscout** [nex3/perspective-el#6]
If you feel like it, could you please add iBuffer support? I use it quite a bit and when in different perspectives, it always displays all the buffers, instead of only those imported.

Thanks!

**Comment by nex3** [comment]
I don't use ibuffer personally, but I'd love a patch that adds support.

**Comment by zenspider** [comment]
I don't use `ibuffer` either. I use `bs-show`, but the idea is the same. They allow you to specify some sort of function or list of functions to filter the current list. I'm refactoring my `bs-show` filters and making them available. Barring a name change, `persp-buffer-filter` should do what you need to do (I just tested it in `ibuffer`).

Closing.
