### ISSUE TITLE
Question around how to use persp-kill

### ISSUE THREAD

**Issue by jojojames** [nex3/perspective-el#60]
```
  ;; Need to skip doing anything if last perspective and last window.
  ;; And also get persp-kill to kill the current perspective instead of forcing interaction.
  (defun delete-perspective-or-window()
    "Delete perspective if last window left but delete window if more than one."
    (interactive)
    (if (eq (count-windows) 1)
        (persp-kill nil) ;; (persp-kill persp-curr)
      (delete-window)))
```
I'm trying to write a wrapper method to selectively call persp-kill or delete-window depending on the window count. (persp-kill nil) works but brings up interaction. I'd prefer (persp-kill) to automatically end kill the perspective.

Also wondering if perspective is exposing another variable to check the number of perspectives currently up.

Thanks!

**Comment by nex3** [comment]
`persp-kill` will only bring up an interactive prompt if you don't pass an explicit name. If you want to kill the current perspective without interaction, you can just call `(persp-kill (persp-name persp-curr))`.

> Also wondering if perspective is exposing another variable to check the number of perspectives currently up.

You can inspect the `perspectives-hash` variable to see the total number of perspectives in the current frame.

**Comment by jojojames** [comment]
Thanks.
