### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by lj-ucb** [nex3/perspective-el#61]
Is it possible to add a perspective tab on the side(something like a neotree), listing the current files/buffers/directory structure inside? 

Motivation for this is that, I often find myself working with a large code base ( lots of files/directories), but at a given time, I am just interested in a few of them, if perspective allows me to easily define/add/delete/modify the perspective definition, that would be a great productivity boost.

**Comment by zenspider** [comment]
I think this is out of scope for perspective. `speedbar`, `sr-speedbar` and friends provide this type of functionality. You just want to filter the buffers by using `(persp-buffers (persp-curr))` (which I really want to make a simple helper function for).

Closing.
