### ISSUE TITLE
It cannot be used with elscreen-persist

### ISSUE THREAD

**Issue by kootenpv** [nex3/perspective-el#62]
It would be a really great feature if it would support `(elscreen-persist)`!

It cannot load, suffering from a `#` on boot.

Steps to reproduce:

1) init persp-mode
2) init elscreen-persist
3) elscreen-persist-store
4) restart emacs, and elscreen-persist-restore

Result is that it chokes on a #

**Comment by zenspider** [comment]
We've recently added our own persistence mechanism (see `persp-state-load`). perspective.el is probably still incompatible with, but supersedes, elscreen-persist.

Closing.
