### ISSUE TITLE
Get a list of perspectives in the modeline/... to act like vim tabs

### ISSUE THREAD

**Issue by vendethiel** [nex3/perspective-el#66]
Hi,

I tend to use perspective (as part of spacemacs) to manage a vim tabs-like environment.
However this approach doesn't give any visual cues as to which perspectives are currently open: you only see the perspective number. Is there a way to see a list?

FTR, this is how it looks on vim:

![](https://cdn.discordapp.com/attachments/233678239896174593/385453854860247040/unknown.png)

**Comment by nex3** [comment]
[`persp-update-modestring`](https://github.com/nex3/perspective-el/blob/89a8ef5e8297b113e4f732bb94336608b76e13fd/perspective.el#L411-L422) should include the perspective names in the modestring. Are you sure you have `persp-show-modestring` set to `t`?

**Comment by vendethiel** [comment]
Oh, I see now. I'm using Spacemacs, and @TheBB's Spaceline doesn't have a fragment for this. I'll go there instead. thank you :)
