### ISSUE TITLE
2.0 update breaks persp-modestring

### ISSUE THREAD

**Issue by chadhs** [nex3/perspective-el#68]
```emacs-lisp
'(persp-modestring persp-modestring)
```

this no longer prints persp-mode info in the modeline.

**Comment by nex3** [comment]
`persp-modestring` is no longer a variable, because Emacs removed support for frame-local variables. Instead, you now have to do `'(:eval (persp-mode-line))`.

**Comment by chadhs** [comment]
works like a charm!  thanks for the help.  :-)
