### ISSUE TITLE
Incompatible with lsp-ui

### ISSUE THREAD

**Issue by kvolkovich-sc** [nex3/perspective-el#79]
Emacs version - 26.1

I use perspective in pair with [lsp-ui](https://github.com/emacs-lsp/lsp-ui).

When [lsp-ui-doc](https://github.com/emacs-lsp/lsp-ui#lsp-ui-doc) feature called (popup with documentation), I got: `error in process filter: persp-add-buffer: Wrong type argument: perspective, nil`.

On MacOS High Sierra in fullscreen mode, desktop workspace with full screen empty Emacs window created after each of error.

On Ubuntu 18.04 (Emacs 25.3.2) I don't know why, but I don't have this error.

I found a topic with similar error and its dated half year ago:
 https://www.reddit.com/r/emacs/comments/93kwtu/how_do_i_debug_a_function_thats_being_called_when/

**Comment by zwild** [comment]
I got the same error. I think that's because the new feature of Emacs 26 - child frames.

**Comment by gcv** [comment]
This should now be fixed.
