### ISSUE TITLE
Not advising buffer-list ?

### ISSUE THREAD

**Issue by zenspider** [nex3/perspective-el#83]
I looked through the open and closed issues for something related to this and didn't find anything.

I'm a little surprised that you're not advising on `buffer-list` as that would be the entry point for many/most 3rd party buffer managers (eg I use `bs` and there are several feature requests for others).

Would this be something you'd like? Or is there a reason not to do it (eg, safety)? I'd like this to support `bs-show` and would have expected that support to be near free, if not automatic via `buffer-list`.

**Comment by dzop** [comment]
How would this work though? If `buffer-list` was advised to return only the buffers of the current perspective how would programs get all the open buffers in Emacs?

I don't use `bs`, but couldn't you integrate `perspective` with it using something like

```emacs-lisp
(defun nn/bs-persp-exclude-buffer (orig buffer)
  (or (funcall orig buffer)
      (not (memq buffer (persp-buffers (persp-curr))))))

(dolist (config bs-configurations)
  (let ((dont-show-fn (or (nth 4 config) #'ignore)))
    (setf (nth 4 config)
          (apply-partially #'nn/bs-persp-exclude-buffer dont-show-fn))))
```

**Comment by zenspider** [comment]
I wound up doing something very similar:

```
(defun rwd/bs-config/persp (buf)
  (with-current-buffer buf
    (not (member buf (persp-buffers (persp-curr))))))

(add-to-list 'bs-configurations '("persp" nil nil "^\\*" rwd/bs-config/persp))
```

Your version has an interesting technique of calling through to the original. I'll have to poke at that, but for now, I'm rather happy with my setup. 

As far as your original question goes about programs not seeing all buffers... yes, exactly. That is what I want. For each perspective to basically look and feel like its own instance of emacs w/o leaking through too much. It may well cause problems if advised in such a way, I dunno.

P.S. I'd never seen `apply-partially` in elisp. Thanks!

**Comment by nex3** [comment]
I haven't tested, but I suspect pretending *everywhere* that no buffers exist outside the current perspective might cause some internal infrastructure problems. Also, it's sometimes useful to do stuff like grab a buffer from another perspective or check all unsaved buffers everywhere before closing the terminal (something inherently cross-perspective). I think doing some bs-specific config is probably your best bet here.
