### ISSUE TITLE
`desktop-read` breaks perspective-mode, and nearly everything else

### ISSUE THREAD

**Issue by zenspider** [nex3/perspective-el#84]
After attempting to run `desktop-read`, with nothing terribly complicated in it, all interactions with perspective, or `switch-to-buffer`, or `debugger-on-error` fail out. The fact that I can't bring up the debugger at all is the sticking point for me. I can't even provide you with any other info but this:

`*Messages*` buffer:

```
Debug on Error enabled globally
ad-handle-definition: ‘imenu’ got redefined
Starting new Ispell process /usr/local/bin/aspell with english dictionary...
Desktop: File "/Users/ryan/Work/git/chef/inspec/results/test.unit.resources.http.test.rb.log" no longer exists.
Desktop: Directory /Users/ryan/Work/git/chef/inspec/results/ no longer exists.
Wrote /Users/ryan/.emacs.d/.emacs.desktop.lock
Desktop: 1 frame, 13 buffers restored, 2 failed to restore.
Entering debugger...
xding
ad-Advice-recursive-edit: Wrong type argument: hash-table-p, "Unprintable entity"
Entering debugger...
xding
ad-Advice-recursive-edit: Wrong type argument: hash-table-p, "Unprintable entity"
Mark set
```

Those last two errors are me trying to use `perspective-switch` and `switch-to-buffer` I believe.

**Comment by gcv** [comment]
@zenspider: Not sure what's going on with your problem there, but don't waste your time trying to use desktop-save-mode with perspective-el. I have a PR for perspective-el which adds comparable save-restore functionality: https://github.com/nex3/perspective-el/pull/80, please test it!

**Comment by azzamsa** [comment]
I also tried desktop-mode but no luck, @gcv know what happened? why?

**Comment by gcv** [comment]
The `Wrong type argument: hash-table-p` error might have occurred because a frame was not properly initialized for perspective-el. In any case, desktop-mode is not supported with perspective. That might change in the future, but in the meanwhile, persp-state-save and persp-state-load from #80. We'll merge that in soon(ish).

**Comment by azzamsa** [comment]
Thanks. Hope that will be merged soon.

**Comment by zenspider** [comment]
I can't reproduce this anymore. I think we've covered our bases. Otherwise, maybe we can get more info if we can reproduce it later. Closing.
