### ISSUE TITLE
Make persp-find-some smarter

### ISSUE THREAD

**Issue by zenspider** [nex3/perspective-el#90]
I'm not thrilled with the way `persp-find-some` works when you're killing off perspectives.

The gist: Let's say you're using this mode (persps sorted chronologically) to do a yak shave and you have several perspectives pushed on the stack. You finish up some of them and start to kill the perspectives. The first time, it uses `persp-last` to switch to the last one you were on. That seems fine. But after that, `persp-last` is `nil` and it goes to `(car (persp-names))` instead. That doesn't really match the workflow for this mode and should be something a bit smarter (newest, or `persp-last` should maintain a stack, or _something_).

_Originally posted by @zenspider in https://github.com/nex3/perspective-el/pull/87#issuecomment-528053148_

**Comment by gcv** [comment]
I wonder if this might be the excuse needed to stop using frame parameters to store state and switch to a global hash table indexed by frame (id). Frame parameters cause other problems, like the one #86 attempts to address. It's kind of a big change, though.

**Comment by gcv** [comment]
Looking at this and thinking about it... doesn't `(persp-names)` respect the sorting order? I just tried it, and perspective killing proceeded in pop-the-stack order. IOW Perspective currently behaves just like description suggests it should, at least for the yak shave workflow. Maybe I'm missing something?

**Comment by gcv** [comment]
Let's reopen if this is still something we need to look at.
