### ISSUE TITLE
Convert perspective-el to lexical scope

### ISSUE THREAD

**Issue by gcv** [nex3/perspective-el#99]
Time to append

```
-*- lexical-binding: t -*-
```

to the first line of `perspective.el`. (And fix whatever breaks as needed.)

**Comment by zenspider** [comment]
# YES PLEASE

**Comment by zenspider** [comment]
I think I'm close. I'm also removing `cl` at the same time. Currently battling with one last test:

```
Test state-save-and-load condition:
    (wrong-type-argument persp--state-complete "#s(persp--state-complete ...))
```

I'm not positive, but maybe something to do with `cl` `defstruct` vs `cl-lib` `cl-defstruct`?

**Comment by zenspider** [comment]
I think I have this now... Gonna bang on it for a while...

**Comment by zenspider** [comment]
Um... potentially stupid question... but how do I know I did it right? Everything SEEMS fine.

😛🤷‍♀️

**Comment by gcv** [comment]
I just set up my work environment with the following PRs and changes in a local "release candidate" branch:

- https://github.com/nex3/perspective-el/pull/95 (stability and cleanup improvement)
- https://github.com/nex3/perspective-el/pull/109 (byte compile warnings)
- https://github.com/nex3/perspective-el/pull/112 (lexical scope switch)

I will run it through its paces as I work over the next day or two. If I don't see any bugs, let's merge all that in. Maybe cut a new version tag for melpa-stable users also — these PRs are all great improvements.

**Comment by gcv** [comment]
The change has been stable for me. Very happy with it.
